### ISSUE TITLE
Error when navigating to new page

### ISSUE THREAD

**Issue by davidfoxio** [EmaSuriano/react-scroll-section#139]
I'm getting the below error in my console when navigating to a new page, from a page that is using react-scroll-section for the other links on the page. Is there any way to bypass react-scroll-section for individual links to avoid this?

ScrollingProvider.js:22 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

**Comment by joernroeder** [comment]
same error here. But I am getting after navigating via react-router to a page with react-scroll-section present.

**Comment by joernroeder** [comment]
After taking a look at the  code I think I see the issue, let me explain in more detail: 
I'm using the dynamic approach where`<Section>` are registering themselves via [`registerRef`](https://github.com/EmaSuriano/react-scroll-section/blob/master/src/Section.tsx#L12) provided by the context provider. But neither the provider nor the Section removes that ref from the `REFS` map at any point.

Below a prototype which fixes the issue by returning not only the `ref` but also a `unregister` function which components can call to unregister themselves.

```js
// patch https://github.com/EmaSuriano/react-scroll-section/blob/master/src/ScrollingProvider.tsx#L70
const registerRef = ({id, meta}: {id: string, meta: unknown}) => {
    const ref = React.createRef<HTMLElement>();
    REFS[id] = ref;
    META[id] = meta;

    var unregister = () => {
        REFS[id] = undefined;
        META[id] = undefined;
        delete REFS[id];
        delete META[id];
    }

    return { ref, unregister };
  };
```

```js
// patch https://github.com/EmaSuriano/react-scroll-section/blob/master/src/Section.tsx#L12

const { ref, unregister } = useMemo(() => registerRef({ id, meta }), [id]);
useEffect(() => () => unregister(), [unregister]);
```

there might be more usages of the `registerRef` function which needs to be patched accordingly but you get the idea.
The unregister function is called as the useEffect [cleanup](https://reactjs.org/docs/hooks-reference.html#cleaning-up-an-effect) function.

@EmaSuriano can you take a look at my patch please. I would love to see this integrated soonish as I have to look into alternative modules otherwise. thank you!

**Comment by joernroeder** [comment]
@EmaSuriano did you find some time to look into this?

**Comment by LiteSoul** [comment]
> same error here. But I am getting after navigating via react-router to a page with react-scroll-section present.

Same is happening to me, after upgrading this from 2.x to 3.x.

**Comment by EmaSuriano** [comment]
Hello guys, I think this issue should be fixed after the latest update on the library. 

I will proceed the issue, please feel free to re-open it again in case there is something missing.
