### ISSUE TITLE
 Cannot read property 'scrollTo' of undefined

### ISSUE THREAD

**Issue by marcosguti** [EmaSuriano/react-scroll-section#27]
i'm geting this error executing build using in gatsby ^2.19.45 and react-scroll-section ^2.0.0
``` ERROR #95313 

Building static HTML failed for path "/404/"

  10 |     null,
  11 |     function (_ref2) {
> 12 |       var scrollTo = _ref2.scrollTo,
     | ^
  13 |           selected = _ref2.selected;
  14 | 
  15 |       var onClick = function onClick() {


  WebpackError: TypeError: Cannot read property 'scrollTo' of undefined
  
  - SectionLink.js:12 Object.children
    node_modules/react-scroll-section/es/SectionLink.js:12:1```


but in local works fine

**Comment by EmaSuriano** [comment]
Hello,@marcosguti I created a [CodeSanbox](https://codesandbox.io/s/react-scroll-section-gatsby-ywk1n) in order to reproduce the issue and I wasn't able to do it. I used the latest version of Gatsby because otherwise the build was not working, at least for me ... 

One last thing, I don't think this issue is connected to the way that Gatsby communicates with the library. By the error message, I'm assuming that you forgot to wrap your `404` screen into the `ScrollingProvider`. 

Let me know if the example was helpful for you and in case the error persist it would be nice to see the code of your component.
