### ISSUE TITLE
Offsetting the scroll to position

### ISSUE THREAD

**Issue by benszucs** [EmaSuriano/react-scroll-section#3]
Hi, when I use the library to scroll to an anchor the nav covers some of the section. I don't want to add padding to the sections to compensate for the height of the nav so was wondering if it was possible to offset the scroll to position of the anchors

**Comment by p32929** [comment]
This is exactly what I have been looking for

**Comment by EmaSuriano** [comment]
Hello sorry for the huge delayed, for some reason I wasn't watching my own repository ... So it's been a while since I don't update this project, and I decided to improve the codebase (documentation, test, etc.) and also add this feature.

Now you can send the property `offset` to the `ScrollSectionProvider`, which then it's going to be added when the browser scrolls to the Section. You can the implementation [here](https://github.com/EmaSuriano/react-scroll-section/blob/master/src/ScrollingProvider.js#L75).

Again, I really don't know if you are still using the library, but I think this is a nice feature to have inside the library.
